esphome:
  name: tubeszb-mgm24
  project:
    name: tubeszb.efr32_mgm24
    version: "2024.03.15"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server
  - source: github://tube0013/esphome-components
    components: [uart]
dashboard_import:
  package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-efr32-MGM24/firmware/ESPHome/tubeszb-mgm24.yaml

#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

#WT32_ETH01 Ethernet
#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO0_IN
#  phy_addr: 1
#  power_pin: GPIO16
  
    # Optional manual IP
  #manual_ip:
    #static_ip: 
    #gateway: 
    #subnet: 255.255.255.0  

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  platform: esphome

web_server:
  port: 80
  local: true
   
switch:
  - platform: gpio
    pin: 5
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
       
  - platform: gpio
    pin: 16
    name: "Pull Bootloader pin (PA0) to Low"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    disabled_by_default: true  
    
button:    
  - platform: restart
    name: "Restart the Gateway"
    disabled_by_default: true

  - platform: template
    name: "EFR32 Reset"
    id: zRST
    disabled_by_default: true  
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

uart:
  id: uart_bus
  rx_pin: GPIO36
  tx_pin: GPIO4
  cts_pin: GPIO13
  rts_pin: GPIO2
  # possible values are
  # - DISABLE = disable hardware flow control
  # - RTS = enable RX hardware flow control (rts)
  # - CTS = enable TX hardware flow control (cts)
  # - CTS_RTS = enable hardware flow control
  # - MAX = ?
  hw_flow_control: CTS_RTS  
  baud_rate: 115200


stream_server:
  uart_id: uart_bus
  port: 6638 # optional, default is 6638
#  buffer_size: 512

binary_sensor:
  - platform: stream_server
    connected:
      name: "TubesZB Serial Connected"
sensor:
  - platform: stream_server
    connection_count:
      name: "Connection Count"

mdns:
  services:
    - service: "_tubeszb"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1.0
        name: TubesZB
        radio_type: ezsp
        baud_rate: 115200
        data_flow_control: hardware
