esphome:
  name: tubeszb-zw
  project: 
    name: tubezb.zw
    version: "3.0"

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server

dashboard_import:
  package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-zw-kit/tubeszb-zw.yaml

#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  
    # Optional manual IP
  #manual_ip:
    #static_ip: 
    #gateway: 
    #subnet: 255.255.255.0  

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80


button:
  - platform: restart
    name: "Restart the ESP32 Device"

uart:
  id: uart_bus
  rx_pin: GPIO16
  tx_pin: GPIO5
  baud_rate: 115200

stream_server:
  buffer_size: 2048
  uart_id: uart_bus
#  id: ss
  port: 6638 # optional, default is 6638


binary_sensor:
  - platform: stream_server
    connected:
      name: "TubesZB ZW Serial Connected"




