esphome:
  name: tubezb-cc2652p2-eth
  project: 
    name: tubezb.cc2652p2-eth
    version: "3.0"

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino


external_components:
  - source: github://tube0013/esphome-stream-server-v2
  - source: github://syssi/esphome-zeroconf@main

dashboard_import:
  package_import_url: github://tube0013/tube_gateways/models/retired/tubeszb-cc2652-eth/firmware/esphome/tubezb-cc2652p2-eth.yaml

#WT32-ETH01 Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

    # Optional manual IP
  #manual_ip:
    #static_ip: 
    #gateway: 
    #subnet: 255.255.255.0  

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:
  port: 80


script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc2538-bsl tool now"
      - logger.log: "cc-bsl usage: cc2538-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex"
      
switch:
  - platform: gpio
    pin: 33
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
      
  - platform: gpio
    pin: 32
    name: "zBSL"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    
  - platform: template
    name: "Prep the cc2652p2 for firmware update"
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - button.press: zRST

button:
  - platform: restart
    name: "Restart the Device"

  - platform: template
    name: "Zigbee Module Reset"
    id: zRST
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

uart:
  id: uart_bus
  rx_pin: GPIO5
  tx_pin: GPIO17
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  id: ss
  port: 6638 # optional, default is 6638

binary_sensor:
  - platform: stream_server
    stream_server: ss
    name: "TubesZB Serial Connected"

zeroconf:
  - service: tubeszb
    protocol: tcp
    port: 6638
    txt:
      version: 1.0
      name: TubesZB
      radio_type: znp
      baud_rate: 115200
      data_flow_control: software

